### ISSUE TITLE
Incomplete Gebers

### ISSUE THREAD

**Issue by DavidIngraham** [tudelft/iridium#1]
First off, thanks for making this awesome piece of hardware open! It opens the doors to some very cool operations.

It seems that the released Gerber files are incomplete. There is no GBO (bottom silkscreen) or paste layers. Would it be possible to provide these? 

Thanks,

David Ingraham

**Comment by dewagter** [comment]
Thank you for your interest. The issue should be solved with 9808fa04a11ecb473359963aeba16ecd684d837c

**Comment by dewagter** [comment]
Attention: accidentally, Revision 1 gerbers were added instead of revision 2. d7844c18a788b5a06bf1a5526d2c530d19a2a9a9 solves this issue.

**Comment by DavidIngraham** [comment]
Great, thank you for that.

One thing that would also be helpful is if you could upload the OBD++ files. These files also contain component placement information that allow for automated manufacturing.

Macrofab has a great guide here on how to export these files from Altium: https://macrofab.com/help/eda-tool-help/altium/

**Comment by dewagter** [comment]
Pick & Place file added, ODB+ and Altium Source

**Comment by fvantienen** [comment]
Are you going to make multiple boards? Is there any chance you could make 1 extra?

**Comment by DavidIngraham** [comment]
Sure, I can manage a group order if you all are interested. We can work out the details over PM.

**Comment by DavidIngraham** [comment]
I'm getting ready to place the order today. There are a few components where the PN on the schematic is different from the PN in the mechanical files. I noticed that the Schematic PDF is R1, is there an updated R2 schematic that I can reference to ensure I am ordering the correct PNs for this version?

**Comment by fvantienen** [comment]
R2 is only a PCB trace change. Which component is a problem?

**Comment by DavidIngraham** [comment]
The two main issues I see:

1. C41 is specified to be a 470uF/6V part but it receives the full input voltage (Up to 8.4V) What part did you actually use?
2. X1 is specified as Farnell Part number 1712829 (Epson Q33310F700245 SG-310SCF) There are conflicting notes that specify a 16MHz Crystal. Just wanted to confirm if this is the correct part number.

**Comment by DavidIngraham** [comment]
Also, I wanted to confirm that the correct part number for the uC is ATMEGA162-16AU

**Comment by dewagter** [comment]
See https://github.com/tudelft/iridium/issues/3
